src/main/java/competition/subsystems/vision/VisionSubsystem.java

Fix X and Y assignment in VisionSubsystem

---

src/main/java/competition/subsystems/arm/ArmPositionSolver.java
src/main/java/competition/subsystems/arm/ArmPositionSolverConfiguration.java
src/main/java/competition/subsystems/arm/ArmPositionState.java
src/test/java/competition/subsystems/arm/ArmPositionSolverTest.java

This uses the cosine law to simply calculate angles.

Add simple arm position solver

---

src/main/java/competition/operator_interface/OperatorInterface.java
src/main/java/competition/subsystems/drive/commands/AutoBalanceCommand.java

Adds a basic command that tries to reach 0 pitch by controlling the drive's y-axis of motion. Will run while the 'Y' button on the drive gamepad is held.
This will almost certainly not work out of the gate, but it's a start.

Auto balance command

---

src/main/deploy/log4j.xml
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java
src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java
src/test/java/competition/subsystems/pose/PoseSubsystemTest.java

- Enable testing for center of rotation
- Allow vision to update heading if it's very confident

Vision can Update Heading

---

src/main/java/competition/electrical_contract/CompetitionContract.java
src/main/java/competition/subsystems/arm/LowerArmSubsystem.java
src/main/java/competition/subsystems/arm/UpperArmSubsystem.java
src/main/java/competition/subsystems/drive/commands/AutoBalanceCommand.java
src/main/java/competition/subsystems/pose/XbotPhotonPoseEstimator.java
src/main/java/competition/subsystems/vision/VisionSubsystem.java

Also Adds correct motor indices to arms

Adds basic rejection to image processing

---

src/main/java/competition/electrical_contract/CompetitionContract.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/arm/ArmSegment.java
src/main/java/competition/subsystems/arm/LowerArmSegment.java
src/main/java/competition/subsystems/arm/UnifiedArmSubsystem.java
src/main/java/competition/subsystems/arm/UpperArmSegment.java

added button to turn brakes for lower arm on and off

Adding Brakes and Brake commands to the Lower Arm

---

src/main/java/competition/subsystems/arm/UnifiedArmSubsystem.java

Lower arm measured from pivot to pivot.
Upper arm measured from pivot to gripper ball joints.

Update arm dimensions.

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java
src/main/java/competition/subsystems/drive/commands/AutoBalanceCommand.java
src/main/java/competition/subsystems/drive/commands/PositionDriveWithJoysticksCommand.java
src/main/java/competition/subsystems/drive/commands/PositionMaintainerCommand.java
src/main/java/competition/subsystems/drive/commands/VelocityDriveWithJoysticksCommand.java
src/main/java/competition/subsystems/drive/commands/VelocityMaintainerCommand.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java

This adds rough/prototype-y drive velocity and position maintainers who only move the robot in the X axis for auto-balancing purposes.
Velocity maintainer tries to maintain an x velocity by controlling the drive motors with power (requires the drive)
Auto balance command tries to set a velocity goal
The position maintainer isn't being used by the balance command yet, it was just controlled via joystick directly for experimenting.
Everything is run by commands on the smart dashboard right now until we get things into a working state where we'll have a command group to run everything probably

Drive X velocity+position maintainers for auto balancing

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/arm/ArmSegment.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java
src/main/java/competition/subsystems/drive/commands/AutoBalanceCommand.java

* Reduces the scope of the AutoBalance command to only work once you're already on the ramp
* Adds a state machine that alternates between climbing the ramp and pausing/braking when it detects severe motion

Automatic Balance State Machine

---

src/main/java/competition/subsystems/arm/UnifiedArmSubsystem.java
src/main/java/competition/subsystems/arm/commands/SimpleSafeArmRouterCommand.java

Choose a facing based on which side of the robot the end effector is on rather than looking solely at the lower arm.

Choose a facing based on which side of the robot the end effector is on

---

src/main/java/competition/Robot.java
src/main/java/competition/electrical_contract/CompetitionContract.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/subsystems/lights/LightsCommunicationSubsystem.java
src/test/java/competition/injection/components/CompetitionTestComponent.java

This is a port of the 2022 ArduinoCommunicationSubsystem.
I removed the shooter wheel at speed and PWM stuff that never worked but it's otherwise the same.

LightsCommunicationSubsystem

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java

set initial heading, heading is modifiable through shuffleboard

Set initial heading 

---

src/main/java/competition/auto_programs/AutoLandmarks.java
src/main/java/competition/auto_programs/BlueBottomScoringPath.java
src/main/java/competition/auto_programs/BlueTopScoringPath.java
src/main/java/competition/auto_programs/RedBottomScoringPath.java
src/main/java/competition/auto_programs/RedTopScoringPath.java

Mirrored blue side travel path to red. Also changed all coordinates to use coordinates from AutoLandmarks.

Mirror blue to red travel path, based coordinates off of landmark library

---

src/main/java/competition/subsystems/arm/commands/UnifiedArmMaintainer.java
src/test/java/competition/subsystems/arm/UnifiedArmMaintainerTest.java

Only engages the brake after the arm has been at its goal position for 1 second.

Only engage LA Brake after a brief period of stability

---

src/main/java/competition/auto_programs/AutoLandmarks.java
src/main/java/competition/auto_programs/EjectLowThenBalanceProgram.java
src/main/java/competition/auto_programs/EjectLowThenBalanceWithMobilityProgram.java
src/main/java/competition/auto_programs/EjectLowThenExitHighProgram.java
src/main/java/competition/auto_programs/EjectLowThenExitLowProgram.java
src/main/java/competition/auto_programs/ParamaterizedAutonomousProgram.java
src/main/java/competition/auto_programs/ParameterizedAutonomousProgram.java
src/main/java/competition/auto_programs/support/AutonomousOracle.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/arm/commands/UnifiedArmMaintainer.java
src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java

Also sets up a ParameterizedAutoCommand that we can iterate on to give the drive team flexibility

Adds more autonomous programs and OI bindings for peace of mind

---

src/main/java/competition/electrical_contract/CompetitionContract.java

Flip upper arm encoder (since it was rotated 180 degrees in its mounting)

Flip upper arm encoder 

---

src/main/java/competition/auto_programs/BlueExitCommunityAndBalanceProgram.java
src/main/java/competition/auto_programs/EjectLowThenBalanceProgram.java
src/main/java/competition/auto_programs/EjectLowThenExitHighProgram.java
src/main/java/competition/auto_programs/EjectLowThenExitLowProgram.java
src/main/java/competition/auto_programs/ScoreCubeHighThenBalanceProgram.java
src/main/java/competition/auto_programs/ScoreCubeHighThenScoreAgainProgram.java
src/main/java/competition/commandgroups/CollectionSequenceCommandGroup.java
src/main/java/competition/commandgroups/ScoreCubeHighCommandGroup.java
src/main/java/competition/electrical_contract/RoboxContract.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/arm/UpperArmSegment.java
src/main/java/competition/subsystems/collector/CollectorSubsystem.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java
src/main/java/competition/subsystems/drive/commands/AutoBalanceCommand.java
src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java
src/main/java/competition/subsystems/drive/commands/VelocityMaintainerCommand.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java
src/test/java/competition/injection/components/CompetitionTestComponent.java
src/test/java/competition/subsystems/drive/VelocityMaintainerCommandTest.java
src/test/java/competition/subsystems/drive/swerve/commands/SwerveDriveWithJoysticksCommandTest.java

* Several fixes to auto programs - lots of little bugs squashed
* Default robot drive power is 75%, with a shoulder button to raise that to 100%
* Changes to the balance program to make it more initially aggressive and behave better when approaching from different sides and/or rotations.

Glacier Peak Day 1

---

src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java

by adding a if statement similar to the unleashed translation power

Unleashed rotation power

---

src/main/java/competition/commandgroups/ScoreConeHighCommandGroup.java
src/main/java/competition/operator_interface/OperatorCommandMap.java

Score cone command group

---

src/main/java/competition/electrical_contract/CompetitionContract.java
src/main/java/competition/electrical_contract/ElectricalContract.java

Update channels for where the lights are plugged in on the rio

Update lightsubsystem dio channels

---

src/main/java/competition/subsystems/pose/PoseSubsystem.java
src/main/java/competition/subsystems/vision/VisionSubsystem.java

(note it won't do anything until the camera is calibrated)

Accept pose from rear april camera

---

src/main/java/competition/electrical_contract/CompetitionContract.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/subsystems/lights/LightsCommunicationSubsystem.java

- change out the alliance bit for isCube, more useful
- rename a bunch of arduino stuff -> Lights

Update LightsSubsystem to use isCube isntead of alliance bit

---

src/main/java/competition/auto_programs/ScoreConeHighThenLeave.java
src/main/java/competition/auto_programs/ScoreConeHighThenScoreCubeHighProgram.java

also wrote another program where it scores cone high then gets mobility points(exits community)

Score cone then cube auto program

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java
src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java

-max drive power from 75 to 90
-precision drive power from 35 to 50
-game piece orientated rotation mode sets center of rotation in front of the robot

Adjust power and add "gamePieceRotationMode"

---

src/main/java/competition/auto_programs/ParameterizedAutonomousProgram.java
src/main/java/competition/subsystems/collector/CollectorSubsystem.java

changed auto default velocity and game piece collected validator

Friday robot changes

---

src/main/java/competition/commandgroups/MoveCollectedGamepieceToArmCommandGroup.java

Used the cone commands to change the cube transfer command to use claw intake to better hold cube

Changed cube transfer command

---

src/main/java/competition/subsystems/arm/UnifiedArmSubsystem.java
src/main/java/competition/subsystems/collector/CollectorSubsystem.java
src/main/java/competition/subsystems/lights/LightsCommunicationSubsystem.java

checks if x coordinate of arm to verify arm is at target position
arm angles were also changed

Arm is at target pos

---

src/main/java/competition/auto_programs/ParameterizedAutonomousProgram.java

Optionally advance auto faster if we get a positive signal that a game piece was collected, and prevent auto from advancing if we fail to acquire any game piece at all.

Optionally advance auto faster if we successfully collect.
